// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XistoreStore.Models;

namespace XistoreStore.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210223164557_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("XistoreStore.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("XistoreStore.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GiftWrap")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("XistoreStore.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "POCO",
                            Description = "6.67 AMOLED(1080x2400) / 2 SIM / Android 10.0 / 2840 МГц(Ядер: 8) / 6Gb / 128Gb / 64 Мп + 12 Мп + 5 Мп + 5 Мп / 4 700 мАч / пурпурный",
                            Name = "Poco F2 Pro",
                            Price = 1699m
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "POCO",
                            Description = "6.67 IPS(1080x2400) / 2 SIM / Android 10.0 / 2300 МГц(Ядер: 8) / 6Gb / 128Gb / 64 Мп + 13 Мп + 2 Мп + 2 Мп / 5 160 мАч / чёрный",
                            Name = "Poco X3",
                            Price = 999m
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Redmi Note",
                            Description = "6.67 IPS (1080x2400) /2 SIM / Android 10 с оболочкой MIUI 11 / 2300 МГц (Ядер: 8) / 6Gb /64Gb / 64 Мп + 8 Мп + 2 Мп + 5 Мп / 5 020 мАч / серый",
                            Name = "Redmi Note 9 Pro",
                            Price = 729m
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Redmi Note",
                            Description = "6.67 (1080x2400) /2 SIM / 2300 МГц (Ядер: 8) / 4Gb /64Gb / 48 Мп + 8 Мп + 5 Мп + 2 Мп / 5 020 мАч / Синяя Мгла",
                            Name = "Redmi Note 9S",
                            Price = 649m
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Redmi Note",
                            Description = "6.53 IPS(1080x2340) / 2 SIM / Android 10 с оболочкой MIUI 11 / 2000 МГц(Ядер: 8) / 3Gb / 64Gb / 48 Мп + 8 Мп + 2 Мп + 2 Мп / 5 020 мАч / серый",
                            Name = "Redmi Note 9",
                            Price = 559m
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Redmi Note",
                            Description = "6.53 IPS (1080x2340) /2 SIM / Android 9 Pie / 2050 МГц (Ядер: 8) / 6Gb /64Gb / 64 Мп + 8 Мп + 2 Мп + 2 Мп / 4 500 мАч / зелёный",
                            Name = "Redmi Note 8 Pro",
                            Price = 649m
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Redmi Note",
                            Description = "6.53 IPS(1080x2340) / 2 SIM / Android 10.0 / (Ядер: 8) / 4Gb / 128Gb / 48 Мп + 2 Мп + 2 Мп / 5 000 мАч / чёрный",
                            Name = "Redmi Note 9T",
                            Price = 799m
                        },
                        new
                        {
                            ProductID = 8,
                            Category = "Redmi",
                            Description = "6.53 IPS(1080x2340) / 2 SIM / Android 10 с оболочкой MIUI 11 / 2000 МГц(Ядер: 8) / 3Gb / 32Gb / 13 Мп + 8 Мп + 2 Мп + 5 Мп / 5 020 мАч / зелёный",
                            Name = "Redmi 9",
                            Price = 449m
                        },
                        new
                        {
                            ProductID = 9,
                            Category = "Redmi",
                            Description = "6.53 IPS(720x1600) / 2 SIM / Android 10.0 / 2000 МГц(Ядер: 8) / 2Gb / 32Gb / 13 Мп / 5 000 мАч / синийй",
                            Name = "Redmi 9A",
                            Price = 299m
                        },
                        new
                        {
                            ProductID = 10,
                            Category = "Redmi",
                            Description = "6.53 IPS(720x1600) / 2 SIM / Android 10 с оболочкой MIUI 12 / 2300 МГц(Ядер: 8) / 3Gb / 64Gb / 13 Мп + 2 Мп + 2 Мп / 5 000 мАч / синий",
                            Name = "Redmi 9C",
                            Price = 399m
                        },
                        new
                        {
                            ProductID = 11,
                            Category = "Mi",
                            Description = "6.67 IPS (1080x2400) /2 SIM / Android 10.0 / 2840 МГц (Ядер: 8) / 8Gb /128Gb / 64 Мп + 13 Мп + 5 Мп / 5 000 мАч / чёрный",
                            Name = "Xiaomi Mi10T",
                            Price = 1499m
                        });
                });

            modelBuilder.Entity("XistoreStore.Models.CartLine", b =>
                {
                    b.HasOne("XistoreStore.Models.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");

                    b.HasOne("XistoreStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("XistoreStore.Models.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
